services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/FinalSCDLab
      - PORT=5000
    volumes:
      - /usr/src/app/node_modules  # Backend node_modules isolation
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - /usr/src/app/node_modules  # Frontend node_modules isolation
    depends_on:
      - backend
    networks:
      - mern-network
    

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge