# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and start services
      run: |
        docker compose up -d --build
        
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 10
        
        # Wait for backend to be ready (up to 60 seconds)
        for i in {1..12}; do
          if curl -f -s http://localhost:5000 > /dev/null 2>&1; then
            echo "Backend is ready!"
            break
          fi
          echo "Waiting for backend... (attempt $i/12)"
          sleep 5
        done
        
        # Wait for frontend to be ready (up to 60 seconds)
        for i in {1..12}; do
          if curl -f -s http://localhost:3000 > /dev/null 2>&1; then
            echo "Frontend is ready!"
            break
          fi
          echo "Waiting for frontend... (attempt $i/12)"
          sleep 5
        done
        
    - name: Test backend
      run: |
        echo "Testing backend endpoint..."
        curl -f -v http://localhost:5000
        
    - name: Test frontend
      run: |
        echo "Testing frontend endpoint..."
        curl -f -v http://localhost:3000
        
    - name: Show running containers
      run: |
        docker ps
        
    - name: Show logs for debugging
      if: failure()
      run: |
        docker compose logs
        
    - name: Cleanup
      if: always()
      run: |
        docker compose down
